#pragma once

#include <game/mLib/m_3d/anm_chr_blend.hpp>
#include <game/mLib/m_3d/anm_chr.hpp>
#include <game/mLib/m_3d/anm_mat_clr.hpp>
#include <game/mLib/m_3d/anm_tex_pat.hpp>
#include <game/mLib/m_3d/anm_tex_srt.hpp>
#include <game/mLib/m_3d/anm_vis.hpp>
#include <game/mLib/m_3d/banm.hpp>
#include <game/mLib/m_3d/bmdl.hpp>
#include <game/mLib/m_3d/calc_ratio.hpp>
#include <game/mLib/m_3d/fanm.hpp>
#include <game/mLib/m_3d/global.hpp>
#include <game/mLib/m_3d/internal.hpp>
#include <game/mLib/m_3d/m_3d_capture.hpp>
#include <game/mLib/m_3d/mdl.hpp>
#include <game/mLib/m_3d/proc.hpp>
#include <game/mLib/m_3d/scn_leaf.hpp>
#include <game/mLib/m_3d/smdl.hpp>
