#!/usr/bin/env python3
# Build script

import argparse
import subprocess
import sys
from pathlib import Path
import json

sys.path.append('tools')

from build_dol import build_dol
from build_rel import build_rel
from color_term import *
from project_settings import *

parser = argparse.ArgumentParser(description='Builds the game executables.')
parser.add_argument('-v', help='Prints commands for debugging', action='store_true')
parser.add_argument('--objdiff-o', help='Object file to build for objdiff')
args = parser.parse_args()

config_json = json.loads(open(BUILDDIR / 'dtkspl/config.json').read())

def build_main(module_name, ldscript, units):
    ldflags = '-proc gekko -fp hard'
    out_file = f'mod/{module_name}'

    file_names = []
    for unit in units:
        if unit['autogenerated']:
            file_names.append(unit['object'])
        else:
            o_file = Path(f'{BUILDDIR}/compiled/{module_name}/{unit['name']}').with_suffix('.o')
            file_names.append(o_file)

    cmd = [] if sys.platform == 'win32' else ['wine']
    cmd.extend([LD, *ldflags.split(' '), *file_names, '-lcf', ldscript, '-o', BUILDDIR / (out_file + '.elf')])
    out = subprocess.run(cmd)
    if out.returncode != 0:
        sys.exit(out.returncode)
    print_success(f'Linked {module_name}.elf.')

def build_module_plf(module_name, ldscript, units):
    ldflags = '-proc gekko -fp hard -sdata 0 -sdata2 0 -m _prolog -r1 -strip_partial'
    out_file = f'mod/{module_name}'
    out_plf = BUILDDIR / (out_file + '.plf')

    file_names: list[Path] = []
    for unit in units:
        if unit['autogenerated']:
            file_names.append(Path(unit['object']))
        else:
            o_file = Path(f'{BUILDDIR}/compiled/{module_name}/{unit['name']}').with_suffix('.o')
            file_names.append(o_file)

    cmd = [] if sys.platform == 'win32' else ['wine']
    cmd.extend([LD, *ldflags.split(' '), *file_names, '-lcf', ldscript, '-o', out_plf])
    out = subprocess.run(cmd)
    if out.returncode != 0:
        sys.exit(out.returncode)
    print_success(f'Linked {module_name}.plf.')

Path(f'{BUILDDIR}/mod').mkdir(parents=True, exist_ok=True)

modules = [BUILDDIR / f'mod/{config_json["name"]}.elf', *[BUILDDIR / f'mod/{x["name"]}.plf' for x in config_json['modules']]]

build_main(config_json['name'], config_json['ldscript'], config_json['units'])
for mods in config_json['modules']:
    build_module_plf(mods['name'], Path(mods['ldscript']), mods['units'])

fake_path = 'd:\\home\\Project\\WIIMJ2D\\EU\\PRD\\RVL\\bin\\'
out_rel_names = [Path(f'{fake_path}/{x.with_suffix(".plf").name}') for x in modules[1:]]
str_path = BUILDDIR / 'mod' / f'{config_json["name"]}.str'
str_path.write_bytes(b'\0'.join(str(p).replace('/', '\\').encode() for p in out_rel_names))

build_dol(BUILDDIR / 'mod' / (config_json['name'] + '.elf'), BUILDDIR / 'mod/main.dol')
print_success('Built main.dol.')
for mod in config_json['modules']:
    build_rel(modules[0], modules[1:], BUILDDIR / 'mod' / (mod['name'] + '.rel'), str_path)
    print_success(f'Built {mod["name"]}.rel.')
