#pragma once
/// @file

/// @addtogroup constants
/// @{

/// @brief Gets the group ID from a message ID.
#define GET_MSG_GROUP(id) ((id) >> 8)

/// @brief Converts a message ID to make it relative to its group ID.
#define GET_MSG_REL_ID(id) ((id) & 0xFF)

/// @brief The identifiers for each text message.
/// @todo Fill this.
enum MESSAGE_e {
    TEST_MESSAGE,

    // The following are used to format escape sequences
    PICTUREFONT_2_BUTTON,
    PICTUREFONT_A_BUTTON,
    PICTUREFONT_1_BUTTON,
    PICTUREFONT_B_BUTTON,
    PICTUREFONT_DPAD,
    PICTUREFONT_HOME_BUTTON,
    PICTUREFONT_PLUS_BUTTON,
    PICTUREFONT_MINUS_BUTTON,
    PICTUREFONT_NUNCHUCK_PAD,
    PICTUREFONT_C_BUTTON,
    PICTUREFONT_Z_BUTTON,
    PICTUREFONT_WIIMOTE,
    PICTUREFONT_NUNCHUK,
    PICTUREFONT_CASTLE,
    PICTUREFONT_TOWER,
    PICTUREFONT_GHOST_HOUSE,
    PICTUREFONT_CANNON,
    PICTUREFONT_AIRSHIP,
    PICTUREFONT_TOAD_HOUSE_RED,
    PICTUREFONT_START_NODE_RIGHT,
    PICTUREFONT_START_NODE_UP,
    PICTUREFONT_MAP_JUNCTION,
    PICTUREFONT_PEACH_CASTLE,
    PICTUREFONT_TOAD_HOUSE_YELLOW,
    PICTUREFONT_TOAD_HOUSE_GREEN,
    PICTUREFONT_LEVEL_NODE_RED,
    PICTUREFONT_LEVEL_NODE_BLUE,
    PICTUREFONT_LEVEL_NODE_YELLOW,
    PICTUREFONT_FINAL_CASTLE,
    PICTUREFONT_AMBUSH,
    PICTUREFONT_SHIP_ANCHOR,
    PICTUREFONT_QUESTION_BLOCK,
    PICTUREFONT_RED_BLOCK,
    PICTUREFONT_BLOCK_OUTLINE,

    HOLD_WIIMOTE_SIDEWAYS = 0x6808,
};

/// @}
