#pragma once
/// @file

/// @addtogroup constants
/// @{

/// @brief The identifiers for each BMG group.
/// @todo Fill this.
enum BMG_GROUPS_e {
    BMG_CATEGORY_YES_NO_WINDOW,
    BMG_CATEGORY_COURSE_SELECT_GUIDE = 4,
    BMG_CATEGORY_CONTROLLER_INFORMATION = 0x68,
    BMG_CATEGORY_HINT_MOVIES = 0x12e
};

/// @brief The identifiers for each text message.
/// @todo Fill this.
enum MESSAGE_e {
    // Group 0x00
    MSG_TEST,

    // The following are used to format escape sequences
    MSG_PICFONT_2_BTN,
    MSG_PICFONT_A_BTN,
    MSG_PICFONT_1_BTN,
    MSG_PICFONT_B_BTN,
    MSG_PICFONT_DPAD,
    MSG_PICFONT_HOME_BTN,
    MSG_PICFONT_PLUS_BTN,
    MSG_PICFONT_MINUS_BTN,
    MSG_PICFONT_NUNCHUCK_PAD,
    MSG_PICFONT_C_BTN,
    MSG_PICFONT_Z_BTN,
    MSG_PICFONT_WIIMOTE,
    MSG_PICFONT_NUNCHUK,
    MSG_PICFONT_CASTLE,
    MSG_PICFONT_TOWER,
    MSG_PICFONT_GHOST_HOUSE,
    MSG_PICFONT_CANNON,
    MSG_PICFONT_AIRSHIP,
    MSG_PICFONT_TOAD_HOUSE_RED,
    MSG_PICFONT_START_NODE_RIGHT,
    MSG_PICFONT_START_NODE_UP,
    MSG_PICFONT_MAP_JUNCTION,
    MSG_PICFONT_PEACH_CASTLE,
    MSG_PICFONT_TOAD_HOUSE_YELLOW,
    MSG_PICFONT_TOAD_HOUSE_GREEN,
    MSG_PICFONT_LEVEL_NODE_RED,
    MSG_PICFONT_LEVEL_NODE_BLUE,
    MSG_PICFONT_LEVEL_NODE_YELLOW,
    MSG_PICFONT_FINAL_CASTLE,
    MSG_PICFONT_AMBUSH,
    MSG_PICFONT_SHIP_ANCHOR,
    MSG_PICFONT_QUESTION_BLOCK,
    MSG_PICFONT_RED_BLOCK,
    MSG_PICFONT_BLOCK_OUTLINE,

    MSG_WATCH_ENDING,
    MSG_YES_IM_SURE,
    MSG_NO_WAIT,
    MSG_OK_TRY,
    MSG_NO_SKIP,
    MSG_OK,
    MSG_CANCEL,
    MSG_SAVE,
    MSG_DONT_SAVE,
    MSG_SAVED_OK,
    MSG_QUICK_SAVE,

    MSG_TRY_WITHOUT_SUPER_GUIDE,
    MSG_PROGRESS_SAVED_FIRST_TIME,
    MSG_TOAD_HOUSES_BACK,
    MSG_ITEM_HINT,
    MSG_SAVE_DATA_CREATED,
    MSG_ASK_SAVE,
    MSG_PROGRESS_SAVED,
    MSG_EXIT_FREE_MODE,
    MSG_WATCH_HINT_MOVIE,
    MSG_SKIP_COURSE,
    MSG_SKIP_FINAL_COURSE,
    MSG_EXIT_COIN_BATTLE,
    MSG_GOT_ALL_STAR_COINS_NO_W9,
    MSG_GOT_ALL_STAR_COINS_W9,
    MSG_TOADS_CAPTURED,
    MSG_RETURN_TO_TITLE,
    MSG_TOADS_CAPTURED_MULTIPLAYER,
    MSG_BACK_TO_MAP,
    MSG_BACK_TO_COURSE_SELECTION,
    MSG_GOT_ALL_STAR_COINS_WORLD_X,
    MSG_RETURN_TO_TITLE_QUICK_SAVE,
    MSG_SAVED_RETURNING_TO_TITLE,
    MSG_COMPLETED_EVERYTHING,
    MSG_BACK_TO_MAP2,

    MSG_SWITCH_FIRST_TIME = 80,
    MSG_SWITCH,
    MSG_PEACH_HINT,
    MSG_PEACH_HINT2,

    // Group 0x04
    MSG_VIEW_MAP = 10,
    MSG_SELECT_WORLD = 11,
    MSG_WM_MENU = 12,
    MSG_BACK_TO_MARIO = 14,
    MSG_ITEMS = 15,
    MSG_COURSE_NUM = 50,
    MSG_COURSE_51 = 51,
    MSG_COURSE_52 = 52,
    MSG_COURSE_53 = 53,
    MSG_WM_WORLD = 60,
    MSG_WM_WORLD_X = 61,

    // Group 0x68
    MSG_HOLD_WIIMOTE_SIDEWAYS = 8,

    // Group 0x12e
    MSG_STAR_COINS_REQUIRED = 7,
    MSG_STAR_COINS_REQUIRED_X = 8,
};

/// @}
